{"id":"01997506-2890-9c23-c9d8-43d046f2de5f","name":"Insert Logger","description":"","icon":"fal fa-square-terminal","tags":[],"permissions":[],"callName":"fts_action_insert_logger","procedureName":"fts_action_insert_logger","parameters":[],"actionLanguage":"SQL","actionCode":"CREATE OR REPLACE FUNCTION fts_action_insert_logger(\n    p_input JSONB\n)\nRETURNS JSONB\n\nLANGUAGE PLPGSQL\nPARALLEL UNSAFE\nVOLATILE\n\nAS $BODY$\n\nDECLARE\n    _record JSONB;\n\nBEGIN\n    RAISE NOTICE 'INSERTING LOGGER: %', p_input;\n\n\tINSERT INTO logger (ref_logger_id, ref_track_id, company, fresh_track_link, fresh_track_link_type)\n    VALUES (p_input->>'ref_logger_id', p_input->>'ref_track_id', p_input->>'company',  p_input->>'freshtrack_link',  p_input->>'freshtrack_link_type')\n    RETURNING to_jsonb(logger.*) INTO _record;\n\n    RETURN fts_sys_build_result(fts_sys_result_data('record', _record));\nEND; $BODY$;"}